import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { Toaster } from '@/components/ui/sonner';
import { ErrorBoundary } from '@/components/layout/error-boundary';
import './globals.css';
import UploadBoundary from '@/components/layout/upload/upload-boundary';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
			>
				<ErrorBoundary>
					<UploadBoundary>
						<main>{children}</main>
						<Toaster richColors />
					</UploadBoundary>
				</ErrorBoundary>
			</body>
		</html>
	);
}
